name: Build libretro core for TrimUI (Linaro GCC 8)

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake libc6-dev libstdc++6

      - name: Install Linaro GCC 8 toolchain
        run: |
          # 下载并安装 Linaro GCC 8.5 工具链
          wget https://releases.linaro.org/components/toolchain/binaries/8.5-2019.12/aarch64-linux-gnu/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
          sudo mkdir -p /opt/linaro
          sudo tar -xJf gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz -C /opt/linaro
          echo "/opt/linaro/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu/bin" >> $GITHUB_PATH
          echo "export PATH=/opt/linaro/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu/bin:\$PATH" >> $GITHUB_ENV
          echo "Toolchain installed to /opt/linaro/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu"

      - name: Verify toolchain
        run: |
          aarch64-linux-gnu-gcc --version
          which aarch64-linux-gnu-gcc

      - name: Build with CMake
        run: |
          export CC=/opt/linaro/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
          export STRIP=/opt/linaro/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-strip
          
          cmake -B build \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=${CC} \
            -DCMAKE_STRIP=${STRIP} \
            -DCMAKE_C_FLAGS="-march=armv8-a -mtune=cortex-a53 -O2 -fPIC" \
            -DLIBRETRO_STATIC=OFF
          cmake --build build -- -j$(nproc)

      - name: Verify output
        run: |
          file build/gam4980_libretro.so
          /opt/linaro/gcc-linaro-8.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-objdump -T build/gam4980_libretro.so | grep GLIBC_

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gam4980_libretro.so
          path: build/gam4980_libretro.so
